javaType:
 String: String
 Long: Long
 Integer: Integer
 Double: String
 java.util.Date: Date
queryType:
 eq: '='
 neq: '!='
 gt: '>'
 ge: '>='
 lt: '<'
 le: '<='
 between: 'between'
 like: 'like'
 left_like: 'left like'
 right_like: 'right Like'
showType:
 input: 单行文本
 textarea: 多行文本
 select: 下拉选项
 hiden: 隐藏域字段
 radiobox: 单选按钮
 checkbox: 复选框
 dateselect: 日期选择
 userselect: 人员选择
 officeselect: 部门选择
 areaselect: 区域选择
 treeselect: 树选择控件
 fileselect: 文件上传选择
validator:
 email:
   name: 电子邮件
   reg: '^[A-Za-z0-9\u4e00-\u9fa5]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$'
 url:
  name: 网址
  reg: '(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?'
 date:
  name: 日期
  reg: '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
 number:
  name: 数值
  reg: '^[-+]?\d+(\.\d+)?$'
 integer:
  name: 整数
  reg: '^-?\d+$'
 digits:
  name: 正整数
  reg: '^\+?[1-9][0-9]*$'
 userName:
  name: 登录账号
  reg: ""
 realName:
  name: 真实姓名
  reg: ""
 abc:
  name: 字母数字下划线
  reg: '^[0-9a-zA-Z_]{1,}$'
 simplePhone:
  name: 固定电话
  reg: '^(0[0-9]{2,3}/-)?([2-9][0-9]{6,7})+(/-[0-9]{1,4})?$'
 phone:
  name: 手机或电话
  reg: '^1[3|4|5|8][0-9]\d{4,8}$'
 zipCode:
  name: 邮政编码
  reg: '[1-9]/d{5}(?!/d)'
 ipv4:
  name: IPv4
  reg: '^((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$'
 ipv6:
  name: IPv6
  reg: '^([\da-fA-F]{1,4}:){7}[\da-fA-F]{1,4}$'
 qq:
  name: QQ
  reg: '[1-9][0-9]{4,}'
 idcard:
  name: 身份证
  reg: '/d{15}|/d{18}'
ftl:
  entity: entity
  mapper: mapper
  dao: dao
  service: service
  restController: restcontroller
  controller: controller
  list: view/ace/list
  form: view/ace/form
  detail: view/ace/detail